-- Camcookie Supabase Schema
-- Provides tables and policies for Connect 26, books, stories, chat, drawings, and profiles.

-- Users table extends Supabase auth users
CREATE TABLE public.users (
  id UUID PRIMARY KEY DEFAULT auth.uid(),
  username VARCHAR(50) UNIQUE NOT NULL,
  full_name VARCHAR(100),
  bio TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read their own profile"
  ON public.users
  FOR SELECT
  USING (auth.uid() = id OR auth.role() = 'authenticated');

CREATE POLICY "Users can update their own profile"
  ON public.users
  FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Authenticated users can insert profiles"
  ON public.users
  FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Books and stories
CREATE TABLE public.stories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  title TEXT NOT NULL,
  summary TEXT,
  body TEXT,
  slug TEXT UNIQUE NOT NULL,
  cover_image_url TEXT,
  is_published BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read stories"
  ON public.stories
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert their own stories"
  ON public.stories
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own stories"
  ON public.stories
  FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own stories"
  ON public.stories
  FOR DELETE
  USING (auth.uid() = user_id);

CREATE TABLE public.story_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story_id UUID NOT NULL,
  tag TEXT NOT NULL,
  FOREIGN KEY (story_id) REFERENCES public.stories(id) ON DELETE CASCADE
);

ALTER TABLE public.story_tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read story tags"
  ON public.story_tags
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert story tags"
  ON public.story_tags
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE TABLE public.story_bookmarks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  story_id UUID NOT NULL,
  user_id UUID NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  FOREIGN KEY (story_id) REFERENCES public.stories(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

ALTER TABLE public.story_bookmarks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read bookmarks"
  ON public.story_bookmarks
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Users can manage own bookmarks"
  ON public.story_bookmarks
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE TABLE public.story_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  story_id UUID NOT NULL,
  user_id UUID NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  FOREIGN KEY (story_id) REFERENCES public.stories(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

ALTER TABLE public.story_comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read story comments"
  ON public.story_comments
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert comments"
  ON public.story_comments
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE TABLE public.organizations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  share_code TEXT UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read organizations"
  ON public.organizations
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE TABLE public.org_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  user_id UUID NOT NULL,
  role TEXT DEFAULT 'member',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

ALTER TABLE public.org_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read their organization memberships"
  ON public.org_members
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own organization membership"
  ON public.org_members
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE TABLE public.chats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID,
  name TEXT NOT NULL,
  is_private BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE SET NULL
);

ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read chats"
  ON public.chats
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE TABLE public.chat_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chat_id UUID NOT NULL,
  user_id UUID NOT NULL,
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  FOREIGN KEY (chat_id) REFERENCES public.chats(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

ALTER TABLE public.chat_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read their chat membership"
  ON public.chat_members
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert chat membership for themselves"
  ON public.chat_members
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE TABLE public.messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chat_id UUID NOT NULL,
  user_id UUID NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  FOREIGN KEY (chat_id) REFERENCES public.chats(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read chat messages"
  ON public.messages
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert own chat messages"
  ON public.messages
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE TABLE public.drawings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  title TEXT,
  drawing_data TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

ALTER TABLE public.drawings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read drawings"
  ON public.drawings
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert own drawings"
  ON public.drawings
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can manage own drawings"
  ON public.drawings
  FOR UPDATE, DELETE
  USING (auth.uid() = user_id);

-- Common indexes
CREATE INDEX idx_stories_slug ON public.stories(slug);
CREATE INDEX idx_story_tags_tag ON public.story_tags(tag);
CREATE INDEX idx_story_bookmarks_user_id ON public.story_bookmarks(user_id);
CREATE INDEX idx_messages_chat_id ON public.messages(chat_id);
CREATE INDEX idx_chat_members_user_id ON public.chat_members(user_id);
CREATE INDEX idx_org_members_user_id ON public.org_members(user_id);
