name: Deploy Maze to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # If you have a build step (e.g. bundler), run it here
      #- name: Build project
      #  run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./maze
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com