name: Run CamcookieBot

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:     # Lets you run manually too

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install beautifulsoup4 requests

      - name: Run CamcookieBot
        run: python camcookiebot.py

      - name: Commit Crawled JSON
        run: |
          git config user.name "CamcookieBot"
          git config user.email "bot@camcookie.com"
          git add data/crawled_pages.json
          git commit -m "🤖 Auto-update crawled data" || echo "No changes"
          git push
